### ISSUE TITLE
Rivinvaihdot kulukorvautuksen perusteeseen PDF:n generoinnissa

### ISSUE THREAD

**Issue by JMALindell** [fyysikkokilta/kulumasiina-v2#8]
Olisi ihan kiva, jos kulukorvautuksen perusteen saisi kokonaisuudessaan kulariin. Helpottaa esim. toiminnantarkastusta.

![image](https://github.com/fyysikkokilta/kulumasiina-v2/assets/99137486/cd77e0fb-27ba-418c-953c-710b45c62d8a)

**Comment by ApsiV11** [comment]
Fixed in 1dd9b5ab7729e0dc52a9ef07210686c0cc61cdb0

![Näyttökuva 2023-12-22 223427](https://github.com/fyysikkokilta/kulumasiina-v2/assets/47868046/d56634fd-80b5-48d1-ba08-4966df567f92)

Also changed the claim title input to textarea in f50615c476bd01800bd10734fa8ecbbb35517b6a to make line breaks work.
